version: "3.8"

services:
  green-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gas-green
    environment:
      - NODE_ENV=production
    ports:
      - "1500:3000"  # Only for debugging

  nginx:
    image: nginx:latest
    container_name: nginx-router
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - green-app
